build:
  environment:
    node:
      version: 12.11.1
  nodes:
    analysis:
      tests:
        override:
          - yarn lint
          - yarn lint:css
          - command: 'CI=true yarn test:coverage'
            coverage:
              file: 'coverage/clover.xml'
              format: 'clover'
